org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
kotlin.compiler.execution.strategy=in-process

# Employee App Release signing
SAFECOM_KEYSTORE=E:/Projects/Working/SafeCom-Application/mobile_employee/android/keystore/safecom-employee.keystore
SAFECOM_KEYSTORE_PASSWORD=safecom123
SAFECOM_KEY_ALIAS=safecom
SAFECOM_KEY_PASSWORD=safecom123