org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=2
android.useAndroidX=true
kotlin.compiler.execution.strategy=in-process

# Customer App Release signing
SAFECOM_KEYSTORE=E:/Projects/Working/SafeCom-Application/mobile_customer/android/keystore/safecom-customer.keystore
SAFECOM_KEYSTORE_PASSWORD=safecom123
SAFECOM_KEY_ALIAS=safecom
SAFECOM_KEY_PASSWORD=safecom123